# Generated by Django 5.2.2 on 2025-06-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='logininfo',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='logininfo',
            name='user_password',
        ),
    ]
