# Generated by Django 5.2.2 on 2025-06-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_signupinfo_remove_logininfo_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupinfo',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
