# Generated by Django 5.2.2 on 2025-06-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_alter_signupinfo_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginInfo',
        ),
        migrations.DeleteModel(
            name='SignupInfo',
        ),
    ]
