# Generated by Django 5.2.2 on 2025-08-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_invalidcredentialslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratelimitlog',
            name='is_throttled',
            field=models.BooleanField(default=False),
        ),
    ]
