# Generated by Django 5.2.2 on 2025-08-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_logincredentiallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidcredentialslog',
            name='is_throttled',
            field=models.BooleanField(default=False),
        ),
    ]
